# Site settings
title: t3hmun's rather simple Jekyll theme
email: gh@t3hmun.com
description: "A Jekyll theme simple enough to understand and edit, even if you find the default Jekyll site complicated. Intended for learning and use."
baseurl: "/rather-simple-jekyll-theme" # the subpath of your site, e.g. /blog/
url: "http://t3hmun.github.io" #"http://yourdomain.com" the base hostname & protocol for your site
twitter_username: # Leaving this blank for fun.
github_username:  t3hmun
footer: Copyright t3hmun (Manish Parekh)

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge